rm(list=ls())
setwd("C:/Users/lenovo/Desktop")
mal<- read.table("exam4.txt",header = TRUE, dec = ",")
View(mal)
#1)
modele1<-lm(irm~ sexe+poids+Total+verbal,data=mal)
#2)
summary(modele1)
#3)
confint(modele1)
#4)
modele2<-lm(irm~ sexe+poids+Total+verbal+perf+taille ,data=mal)
summary(modele2)
#5)
anova(modele1,modele2)
AIC(modele1)
AIC(modele2)
#6)
m0=lm(irm~1,data=mal)
mc=modele2
B=step(mc,direction ="backward" )#descendante
summary(B)
F=step(m0,scope=list(lower=m0, upper=mc), direction ="forward" )
summary(F)
M=step(m0,scope=list(upper=mc), direction = "both")
summary(M)
AIC(F)
AIC(B)
AIC(mc)
AIC(M)
AIC(m0)
BIC(F)
BIC(B)
summary(B)
summary(F)
